name: Pipeline - Pre-release

on:
  release:
    types:
      - prereleased

permissions:
  contents: read
  id-token: write

jobs:
  backendCI:
    uses: thararaoganji/gh-pkg-test/.github/workflows/ci-java.yaml@main
    with:
      environment: dev
      java-version: "17"
      working-directory: .
      publish-to-gh: true
    secrets: inherit